import '@testing-library/jest-dom';
import { render, screen } from '@testing-library/react';

import ErrorBoundary from '../../components/ErrorBoundary';
import { LABELS } from '../../constans';

const Child = () => {
  throw new Error();
};
describe('<ErrorBoundary>', () => {
  it('displays error message on error generated by child', () => {
    render(
      <ErrorBoundary>
        <Child />
      </ErrorBoundary>
    );
    expect(screen.getByRole('heading')).toHaveTextContent(LABELS.ERROR_TEXT);
  });
  it('should not displays error message on valid child', () => {
    render(
      <ErrorBoundary>
        <h1>Hello</h1>
      </ErrorBoundary>
    );
    expect(screen.getByRole('heading')).toHaveTextContent('Hello');
  });
});
